name: drift_driver
description: "Drift Driver App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^9.1.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  google_sign_in: ^6.2.1
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  flutter_map: ^8.2.2
  http: ^1.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  shared_preferences: ^2.2.0
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Light.ttf
          weight: 500
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-SemiBold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Bold.ttf
          weight: 900

flutter_native_splash:
  color: "#04091C"
  image: assets/images/drift_logo.png
  fullscreen: true
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/drift_logo.png
    icon_background_color: "#04091C"
    image_dark: assets/images/drift_logo.png
  branding: assets/images/drift_logo.png
  branding_mode: bottom

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/drift_logo.png"
  adaptive_icon_background: "#04091C"
  adaptive_icon_foreground: "assets/images/drift_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  android_icon_name: "ic_launcher"
