// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Same Firebase project as the User App (drift-11)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2PK_-jYoQDlcFk5TP-9yUvH6FIGnhyqE',
    appId: '1:780867026107:web:aa512887e6c246259abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    authDomain: 'drift-11.firebaseapp.com',
    storageBucket: 'drift-11.firebasestorage.app',
    measurementId: 'G-MBD5HMJR6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3uTb3WljJoBhgyFcRYWGGbyj9qkqciic',
    appId: '1:780867026107:android:295bbcfb86e5ca259abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    storageBucket: 'drift-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLX2XoAFYseYcT-1RUSlfhM5_eGoYO6Ck',
    appId: '1:780867026107:ios:7eca4870559d21239abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    storageBucket: 'drift-11.firebasestorage.app',
    androidClientId: '780867026107-13jvak9rmu88u42ju6hffq7rack89qus.apps.googleusercontent.com',
    iosClientId: '780867026107-b32lvnd2bfie242u0lsprp0v1fo968f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.driftDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLX2XoAFYseYcT-1RUSlfhM5_eGoYO6Ck',
    appId: '1:780867026107:ios:7eca4870559d21239abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    storageBucket: 'drift-11.firebasestorage.app',
    androidClientId: '780867026107-13jvak9rmu88u42ju6hffq7rack89qus.apps.googleusercontent.com',
    iosClientId: '780867026107-b32lvnd2bfie242u0lsprp0v1fo968f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.driftDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2PK_-jYoQDlcFk5TP-9yUvH6FIGnhyqE',
    appId: '1:780867026107:web:71ef462c958eb7059abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    authDomain: 'drift-11.firebaseapp.com',
    storageBucket: 'drift-11.firebasestorage.app',
    measurementId: 'G-DTQK9J5139',
  );

}